In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([[1,2,3,4],[5,6,7,8]], dtype='int8')
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
a.ndim

1

In [5]:
b.shape

(2, 4)

In [6]:
a.dtype

dtype('int64')

In [7]:
c = np.array([1,2,3,4,5], dtype='int8')
print(a)

[1 2 3 4 5]


In [8]:
c.dtype

dtype('int8')

In [9]:
a.itemsize

8

In [10]:
b.itemsize

1

In [11]:
c.itemsize

1

In [12]:
b.size

8

In [13]:
a.size

5

In [14]:
c.size

5

Accessing/Changing specific rows and columns

In [15]:
ac_ch = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
ac_ch

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
ac_ch[1,5]

12

In [40]:
ac_ch[0, :]

array([1, 2, 3, 4, 5, 6])

In [41]:
ac_ch[:, 2]

array([3, 9])

In [42]:
ac_ch[0, 1:6:2]

array([2, 4, 6])